language: android
dist: trusty
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-21
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-29
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
script:
  - ./gradlew build jacocoTestReport testDebug assembleDebug assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)

