language: android
env:
  global:
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
script:
  - ./gradlew build jacocoTestReport mergeJacocoReports jacocoTestReportMerged assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash) -t a0a4dcd1-8a93-4443-8467-8a0fec0fec01
